CREATE TABLE `_ZZ_DELETE_LATER_summary_listeners_by_campaign` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `campaign_id` bigint(20) DEFAULT NULL,
  `status_not_active` int(11) DEFAULT NULL,
  `status_active` int(11) DEFAULT NULL,
  `status_lost` int(11) DEFAULT NULL,
  `active_by_new` int(11) DEFAULT NULL,
  `active_by_return` int(11) DEFAULT NULL,
  `frequency_listen_dialy` int(11) DEFAULT NULL,
  `frequency_listen_weekly` int(11) DEFAULT NULL,
  `frequency_unknown` int(11) DEFAULT NULL,
  `frequency_0_to_5_minutes_per_day` int(11) DEFAULT NULL,
  `frequency_5_to_20_minutes_per_day` int(11) DEFAULT NULL,
  `frequency_20_to_60_minutes_per_day` int(11) DEFAULT NULL,
  `frequency_more_60_minutes_per_day` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `_ZZ_DELETE_LATER_summary_sessions_by_gateway` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date DEFAULT NULL,
  `hour` int(11) DEFAULT NULL,
  `gateway_id` bigint(20) DEFAULT NULL,
  `country_id` bigint(20) DEFAULT NULL,
  `language_id` bigint(20) DEFAULT NULL,
  `rca_id` bigint(20) DEFAULT NULL,
  `broadcast_id` bigint(20) DEFAULT NULL,
  `sessions` bigint(20) DEFAULT NULL,
  `sessions_acd_10sec` mediumint(9) DEFAULT NULL,
  `sessions_acd_1min` mediumint(9) DEFAULT NULL,
  `sessions_acd_5min` mediumint(9) DEFAULT NULL,
  `sessions_acd_20min` mediumint(9) DEFAULT NULL,
  `sessions_acd_1hr` mediumint(9) DEFAULT NULL,
  `sessions_acd_2hr` mediumint(9) DEFAULT NULL,
  `sessions_acd_6hr` mediumint(9) DEFAULT NULL,
  `sessions_acd_more6hr` mediumint(9) DEFAULT NULL,
  `seconds` mediumint(9) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_summary_minutes_listen_sessions_gateway_5_idx` (`broadcast_id`),
  KEY `fk_summary_minutes_listen_sessions_gateway_2_idx` (`country_id`),
  KEY `datehr` (`date`,`hour`),
  KEY `date` (`date`),
  KEY `fk_summary_minutes_listen_sessions_gateway_1_idx` (`gateway_id`),
  KEY `fk_summary_minutes_listen_sessions_gateway_3_idx` (`language_id`),
  KEY `fk_summary_minutes_listen_sessions_gateway_4_idx` (`rca_id`)
) ENGINE=InnoDB AUTO_INCREMENT=161 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `aggregate_custom` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(19) unsigned DEFAULT NULL,
  `removable_id` int(11) DEFAULT NULL,
  `removable_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `remove_children` tinyint(1) DEFAULT '0',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_aggregate_custom_on_removable_id_and_removable_type` (`removable_id`,`removable_type`),
  KEY `index_aggregate_custom_on_removable_id` (`removable_id`),
  KEY `index_aggregate_custom_on_removable_type` (`removable_type`),
  KEY `index_aggregate_custom_on_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `api_keys` (
  `access_token` char(255) NOT NULL,
  `user_id` bigint(19) unsigned NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `expires_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  UNIQUE KEY `access_token_UNIQUE` (`access_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_campaign` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) CHARACTER SET latin1 DEFAULT NULL,
  `advertise_agency_id` bigint(19) unsigned DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '0',
  `limit_date_start` date DEFAULT NULL,
  `limit_date_stop` date DEFAULT NULL,
  `limit_budget_limit` double DEFAULT '0',
  `limit_budget_balance` double DEFAULT '100',
  `limit_play_interruption_per_unique_listener_count_limit` int(10) unsigned DEFAULT '0',
  `limit_play_interruption_per_unique_listener_minutes_window` int(10) unsigned DEFAULT '0',
  `playslot_A_play_interruption_cost_per_play` float unsigned DEFAULT '0',
  `playslot_A_play_request_cost_per_play` float unsigned DEFAULT '0',
  `playslot_A_play_request_cost_per_unique_listener` float unsigned DEFAULT '0',
  `playslot_B_play_interruption_cost_per_play` float unsigned DEFAULT '0',
  `playslot_B_play_request_cost_per_play` float unsigned DEFAULT '0',
  `playslot_B_play_request_cost_per_unique_listener` float unsigned DEFAULT '0',
  `playslot_C_play_interruption_cost_per_play` float unsigned DEFAULT '0',
  `playslot_C_play_request_cost_per_play` float unsigned DEFAULT '0',
  `playslot_C_play_request_cost_per_unique_listener` float unsigned DEFAULT '0',
  `playslot_D_play_interruption_cost_per_play` float unsigned DEFAULT '0',
  `playslot_D_play_request_cost_per_play` float unsigned DEFAULT '0',
  `playslot_D_play_request_cost_per_unique_listener` float unsigned DEFAULT '0',
  `playmatrix_sunday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_sunday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_monday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_tuesday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_wednesday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_thursday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_friday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_00` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_01` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_02` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_03` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_04` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_05` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_06` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_07` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_08` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_09` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_10` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_11` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_12` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_13` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_14` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_15` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_16` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_17` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_18` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_19` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_20` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_21` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_22` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `playmatrix_saturday_23` enum('A','B','C','D') CHARACTER SET latin1 DEFAULT 'A',
  `advertise_interruption_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `advertise_request_type` enum('PROMPT','SIPTRANSFER') CHARACTER SET latin1 DEFAULT 'PROMPT',
  `advertise_request_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `advertise_request_siptransfer_sip_string` char(255) CHARACTER SET latin1 DEFAULT NULL,
  `advertise_request_siptransfer_callid_mode` enum('CLEAN','LISTENERANI','LISTENERID') CHARACTER SET latin1 DEFAULT 'LISTENERID',
  `advertise_request_siptransfer_preconnect_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `advertise_request_siptransfer_failconnect_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `date_last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `allow_listener_preroll_trigger` tinyint(1) DEFAULT '1',
  `allow_listener_timeout_trigger` tinyint(1) DEFAULT '1',
  `allow_listener_request_trigger` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `dispatcher_1` (`is_active`),
  KEY `dispatcher_2` (`limit_date_start`,`limit_date_stop`),
  KEY `dispatcher_3` (`limit_budget_limit`,`limit_budget_balance`),
  KEY `fk_data_campaign_1_idx` (`advertise_agency_id`),
  CONSTRAINT `fk_data_campaign_1` FOREIGN KEY (`advertise_agency_id`) REFERENCES `data_group_advertise_agency` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE `data_campaign_prompt` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `campaign_id` bigint(19) unsigned DEFAULT NULL,
  `media_kb` int(10) unsigned DEFAULT '0',
  `media_seconds` int(10) unsigned DEFAULT '0',
  `date_last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

CREATE TABLE `data_campaign_prompt_blob` (
  `id` bigint(19) unsigned NOT NULL,
  `binary` longblob,
  `last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_campaign_publishmap_simple` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `campaign_id` bigint(19) unsigned DEFAULT NULL,
  `type` enum('ACCEPT','REJECT') DEFAULT NULL,
  `field` enum('ENTRYWAY_ID','GATEWAY_ID','CONTENT_ID','ENTRYWAY_PROVIDER_ID','3RDPARTY_ID','BROADCAST_ID','COUNTRY_ID','GENRE_ID','LANGUAGE_ID','RCA_ID','LISTENER_ANI_CARRIER_ID','CAMPAIGN_PLAYSLOT','LISTENER_IS_ANONYMOUS') DEFAULT NULL,
  `operator` enum('EQUAL','NOT_EQUAL','IN_CSV_LIST','NOT_IN_CSV_LIST','IS_EMPTY','IS_NOT_EMPTY','IS_TRUE','IS_FALSE') DEFAULT NULL,
  `value` varchar(8192) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `campaign` (`campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_content` (
  `id` bigint(19) unsigned NOT NULL,
  `title` char(200) DEFAULT NULL,
  `broadcast_id` bigint(19) unsigned DEFAULT NULL,
  `country_id` bigint(19) unsigned DEFAULT NULL,
  `language_id` bigint(19) unsigned DEFAULT NULL,
  `genre_id` bigint(19) unsigned DEFAULT NULL,
  `media_type` char(16) DEFAULT 'SHOUTCAST',
  `media_url` char(255) DEFAULT NULL,
  `metadata_name` char(255) DEFAULT NULL,
  `metadata_genre` char(255) DEFAULT NULL,
  `metadata_website` char(255) DEFAULT NULL,
  `metadata_public` char(32) DEFAULT NULL,
  `metadata_bitrate` char(32) DEFAULT NULL,
  `metadata_track_title` char(255) DEFAULT NULL,
  `metadata_track_url` char(255) DEFAULT NULL,
  `metadata_last_check_date` timestamp NULL DEFAULT NULL,
  `metadata_last_check_server_id` bigint(19) unsigned DEFAULT NULL,
  `metadata_track_last_check_date` timestamp NULL DEFAULT NULL,
  `metadata_track_last_check_server_id` bigint(19) unsigned DEFAULT NULL,
  `flag_no_listener_preroll_ad` tinyint(1) DEFAULT '0',
  `flag_no_listener_timeout_ad` tinyint(1) DEFAULT '0',
  `date_last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_data_content_1_idx` (`broadcast_id`),
  KEY `fk_data_content_1_idx1` (`country_id`),
  KEY `fk_data_content_1_idx2` (`language_id`),
  KEY `gener_idx` (`genre_id`),
  CONSTRAINT `fk_data_content_2` FOREIGN KEY (`country_id`) REFERENCES `data_group_country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_content_1` FOREIGN KEY (`broadcast_id`) REFERENCES `data_group_broadcast` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_content_3` FOREIGN KEY (`language_id`) REFERENCES `data_group_language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_content_4` FOREIGN KEY (`genre_id`) REFERENCES `data_group_genre` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_content_media_fail` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `server_id` bigint(19) unsigned DEFAULT NULL,
  `content_id` bigint(19) unsigned DEFAULT NULL,
  `type` char(32) DEFAULT NULL,
  `url_at_event` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_entryway` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `did_e164` char(32) DEFAULT NULL,
  `gateway_id` bigint(19) unsigned DEFAULT NULL,
  `country_id` bigint(19) unsigned DEFAULT NULL,
  `3rdparty_id` bigint(19) unsigned DEFAULT NULL,
  `entryway_provider` bigint(19) unsigned DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `is_default` tinyint(1) DEFAULT '0',
  `flag_no_listener_preroll_ad` tinyint(1) DEFAULT '0',
  `flag_no_listener_timeout_ad` tinyint(1) DEFAULT '0',
  `date_last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `DID` (`did_e164`),
  KEY `title` (`title`),
  KEY `fk_data_entryway_1_idx` (`entryway_provider`),
  KEY `fk_data_entryway_1_idx1` (`gateway_id`),
  KEY `fk_data_entryway_1_idx2` (`3rdparty_id`),
  KEY `fk_data_entryway_1_idx3` (`country_id`),
  KEY `gateway_idx` (`gateway_id`),
  CONSTRAINT `3rdparty` FOREIGN KEY (`3rdparty_id`) REFERENCES `data_group_3rdparty` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `country` FOREIGN KEY (`country_id`) REFERENCES `zenoradio-v25`.`data_group_country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `entreway_provider` FOREIGN KEY (`entryway_provider`) REFERENCES `data_entryway_provider` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `gateway` FOREIGN KEY (`gateway_id`) REFERENCES `data_gateway` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=26886 DEFAULT CHARSET=utf8;

CREATE TABLE `data_entryway_provider` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

CREATE TABLE `data_gateway` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `country_id` bigint(19) unsigned DEFAULT NULL,
  `language_id` bigint(19) unsigned DEFAULT NULL,
  `broadcast_id` bigint(19) unsigned DEFAULT NULL,
  `rca_id` bigint(19) unsigned DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `empty_extension_rule` enum('ASK_AGAIN','PLAY_FIRST') DEFAULT 'PLAY_FIRST',
  `empty_extension_threshold_count` tinyint(3) unsigned DEFAULT '2',
  `invalid_extension_rule` enum('ASK_AGAIN','PLAY_FIRST') DEFAULT 'PLAY_FIRST',
  `invalid_extension_threshold_count` tinyint(3) unsigned DEFAULT '3',
  `ivr_welcome_enabled` tinyint(1) DEFAULT '1',
  `ivr_welcome_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `ivr_extension_ask_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `ivr_extension_invalid_enabled` tinyint(1) DEFAULT '1',
  `ivr_extension_invalid_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `flag_no_listener_preroll_ad` tinyint(1) DEFAULT '0',
  `flag_no_listener_timeout_ad` tinyint(1) DEFAULT '0',
  `date_last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_data_gateway_1_idx` (`country_id`),
  KEY `fk_data_gateway_2_idx` (`language_id`),
  KEY `fk_data_gateway_3_idx` (`broadcast_id`),
  KEY `fk_data_gateway_4_idx` (`rca_id`),
  KEY `fk_data_gateway_5_idx` (`ivr_welcome_prompt_id`),
  KEY `fk_data_gateway_6_idx` (`ivr_extension_ask_prompt_id`),
  KEY `fk_data_gateway_7_idx` (`ivr_extension_invalid_prompt_id`),
  CONSTRAINT `fk_data_gateway_1` FOREIGN KEY (`country_id`) REFERENCES `zenoradio-v25`.`data_group_country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_2` FOREIGN KEY (`language_id`) REFERENCES `data_group_language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_3` FOREIGN KEY (`broadcast_id`) REFERENCES `data_group_broadcast` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_4` FOREIGN KEY (`rca_id`) REFERENCES `data_group_rca` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_5` FOREIGN KEY (`ivr_welcome_prompt_id`) REFERENCES `zenoradio-v25`.`data_gateway_prompt` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_6` FOREIGN KEY (`ivr_extension_ask_prompt_id`) REFERENCES `zenoradio-v25`.`data_gateway_prompt` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_7` FOREIGN KEY (`ivr_extension_invalid_prompt_id`) REFERENCES `zenoradio-v25`.`data_gateway_prompt` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2091 DEFAULT CHARSET=utf8;

CREATE TABLE `data_gateway_conference` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `gateway_id` bigint(19) unsigned DEFAULT NULL,
  `content_id` bigint(19) unsigned DEFAULT NULL,
  `extension` char(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_data_gateway_content_1_idx` (`gateway_id`),
  KEY `fk_data_gateway_content_2_idx` (`content_id`),
  CONSTRAINT `fk_data_gateway_content_1` FOREIGN KEY (`gateway_id`) REFERENCES `data_gateway` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_gateway_content_2` FOREIGN KEY (`content_id`) REFERENCES `data_content` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=14416 DEFAULT CHARSET=utf8;

CREATE TABLE `data_gateway_prompt` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `gateway_id` bigint(19) unsigned DEFAULT NULL,
  `media_kb` int(10) unsigned DEFAULT '0',
  `media_seconds` int(10) unsigned DEFAULT '0',
  `date_last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_data_gateway_prompt_1_idx` (`gateway_id`),
  CONSTRAINT `fk_data_gateway_prompt_1` FOREIGN KEY (`gateway_id`) REFERENCES `data_gateway` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6232 DEFAULT CHARSET=utf8;

CREATE TABLE `data_gateway_prompt_blob` (
  `id` bigint(19) unsigned NOT NULL,
  `binary` longblob,
  `last_change` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_3rdparty` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1089654 DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_advertise_agency` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_broadcast` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1102843 DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_country` (
  `id` bigint(19) unsigned NOT NULL,
  `title` char(200) DEFAULT NULL COMMENT 'get data from here http://en.wikipedia.org/wiki/ISO_3166-1',
  `iso_alpha_2` char(2) DEFAULT NULL,
  `iso_alpha_3` char(3) DEFAULT NULL,
  `iso_numeric` char(3) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_genre` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_language` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `data_group_rca` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1095200 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `flag_push_marketing_opt_in` tinyint(1) DEFAULT '0',
  `area_code` char(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1211170 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener_ani` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `ani_e164` char(64) DEFAULT NULL,
  `carrier_id` bigint(19) unsigned DEFAULT NULL,
  `carrier_last_check` datetime DEFAULT NULL,
  `carrier_OCN` char(32) DEFAULT NULL COMMENT 'PLEASE DO NOT USE THIS FIELD.\nDuplicate relationship. Wil be deleted in future.\n',
  PRIMARY KEY (`id`),
  KEY `fk_data_listener_ani_1_idx` (`listener_id`),
  KEY `fk_data_listener_ani_2_idx` (`carrier_id`),
  KEY `lastcheck` (`carrier_last_check`),
  KEY `ani` (`ani_e164`),
  CONSTRAINT `fk_data_listener_ani_1` FOREIGN KEY (`listener_id`) REFERENCES `data_listener` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_listener_ani_2` FOREIGN KEY (`carrier_id`) REFERENCES `data_listener_ani_carrier` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1211170 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener_ani_carrier` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `OCN` char(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index2` (`OCN`)
) ENGINE=InnoDB AUTO_INCREMENT=1253 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener_at_campaign` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `context_at_id` bigint(19) unsigned DEFAULT NULL,
  `statistics_first_session_date` timestamp NULL DEFAULT NULL,
  `statistics_last_session_date` datetime DEFAULT NULL,
  `statistics_interruption_first_session_date` datetime DEFAULT NULL,
  `statistics_interruption_last_session_date` datetime DEFAULT NULL,
  `statistics_interruption_last_sessions_timestamp` varchar(1024) DEFAULT NULL,
  `statistics_interruption_last_sessions_log_campaign_id` varchar(1024) DEFAULT NULL,
  `statistics_interruption_sessions_count` bigint(19) unsigned DEFAULT NULL,
  `statistics_interruption_sessions_seconds` bigint(19) unsigned DEFAULT NULL,
  `statistics_request_first_session_date` datetime DEFAULT NULL,
  `statistics_request_last_session_date` datetime DEFAULT NULL,
  `statistics_request_last_sessions_timestamp` varchar(1024) DEFAULT NULL,
  `statistics_request_last_sessions_log_campaign_id` varchar(1024) DEFAULT NULL,
  `statistics_request_sessions_count` bigint(19) unsigned DEFAULT NULL,
  `statistics_request_sessions_seconds` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index2` (`statistics_first_session_date`),
  KEY `fk_data_listener_at_campaign_1_idx` (`listener_id`),
  CONSTRAINT `fk_data_listener_at_campaign_1` FOREIGN KEY (`listener_id`) REFERENCES `data_listener` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=26376 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener_at_content` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `context_at_id` bigint(19) unsigned DEFAULT NULL,
  `statistics_first_session_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `statistics_last_session_date` datetime DEFAULT NULL,
  `statistics_last_sessions_timestamp` varchar(1024) DEFAULT NULL,
  `statistics_last_sessions_log_listen_id` varchar(1024) DEFAULT NULL,
  `statistics_sessions_count` bigint(19) unsigned DEFAULT NULL,
  `statistics_sessions_seconds` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index5` (`statistics_last_session_date`),
  KEY `fk_data_listener_at_content_1_idx` (`listener_id`),
  KEY `fk_data_listener_at_content_2_idx` (`context_at_id`),
  CONSTRAINT `fk_data_listener_at_content_1` FOREIGN KEY (`listener_id`) REFERENCES `data_listener` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_listener_at_content_2` FOREIGN KEY (`context_at_id`) REFERENCES `data_content` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=211066 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener_at_entryway` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `context_at_id` bigint(19) unsigned DEFAULT NULL,
  `statistics_first_session_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `statistics_last_session_date` datetime DEFAULT NULL,
  `statistics_last_sessions_timestamp` varchar(1024) DEFAULT NULL,
  `statistics_last_sessions_log_listen_id` varchar(1024) DEFAULT NULL,
  `statistics_sessions_count` bigint(19) unsigned DEFAULT NULL,
  `statistics_sessions_seconds` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index4` (`statistics_last_session_date`),
  KEY `fk_data_listener_at_entryway_1_idx` (`listener_id`),
  KEY `fk_data_listener_at_entryway_2_idx` (`context_at_id`),
  CONSTRAINT `fk_data_listener_at_entryway_1` FOREIGN KEY (`listener_id`) REFERENCES `data_listener` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_listener_at_entryway_2` FOREIGN KEY (`context_at_id`) REFERENCES `data_entryway` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=102495 DEFAULT CHARSET=utf8;

CREATE TABLE `data_listener_at_gateway` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `context_at_id` bigint(19) unsigned DEFAULT NULL,
  `statistics_first_session_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `statistics_last_session_date` datetime DEFAULT NULL,
  `statistics_last_sessions_timestamp` varchar(1024) DEFAULT NULL,
  `statistics_last_sessions_log_listen_id` varchar(1024) DEFAULT NULL,
  `statistics_sessions_count` bigint(19) unsigned DEFAULT NULL,
  `statistics_sessions_seconds` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index4` (`statistics_last_session_date`),
  KEY `fk_data_listener_at_gateway_1_idx` (`listener_id`),
  KEY `fk_data_listener_at_gateway_2_idx` (`context_at_id`),
  CONSTRAINT `fk_data_listener_at_gateway_1` FOREIGN KEY (`listener_id`) REFERENCES `data_listener` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_listener_at_gateway_2` FOREIGN KEY (`context_at_id`) REFERENCES `data_gateway` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=98919 DEFAULT CHARSET=utf8;

CREATE TABLE `log_call` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `server_id` bigint(19) unsigned DEFAULT NULL,
  `asterisk_remote_ip` char(15) DEFAULT NULL,
  `date_start` datetime DEFAULT NULL,
  `date_stop` datetime DEFAULT NULL,
  `seconds` int(10) unsigned DEFAULT NULL,
  `ani_e164` char(64) DEFAULT NULL,
  `did_e164` char(64) DEFAULT NULL,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `listener_ani_id` bigint(19) unsigned DEFAULT NULL,
  `listener_is_anonymous` tinyint(1) DEFAULT '0',
  `entryway_id` bigint(19) unsigned DEFAULT NULL,
  `gateway_id` bigint(19) unsigned DEFAULT NULL,
  `on_summary` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `date_start` (`date_start`),
  KEY `date_stop` (`date_stop`),
  KEY `server` (`server_id`,`date_start`),
  KEY `listener` (`listener_id`,`date_start`),
  KEY `list_ani` (`listener_ani_id`,`date_start`),
  KEY `entryway` (`entryway_id`,`date_start`),
  KEY `gateway` (`gateway_id`,`date_start`),
  KEY `on_summary` (`on_summary`)
) ENGINE=InnoDB AUTO_INCREMENT=661418 DEFAULT CHARSET=utf8;

CREATE TABLE `log_campaign` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `log_call_id` bigint(19) unsigned DEFAULT NULL,
  `log_listen_id` bigint(19) unsigned DEFAULT NULL,
  `date_start` datetime DEFAULT NULL,
  `date_stop` datetime DEFAULT NULL,
  `campaign_id` bigint(19) unsigned DEFAULT NULL,
  `trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `advertise_prompt_id` bigint(19) unsigned DEFAULT NULL,
  `listener_id` bigint(19) unsigned DEFAULT NULL,
  `listener_is_anonymous` tinyint(1) DEFAULT NULL,
  `listener_interruption_play_count` bigint(19) unsigned DEFAULT '0',
  `listener_request_play_count` bigint(19) unsigned DEFAULT NULL,
  `seconds` int(10) unsigned DEFAULT '0',
  `seconds_played` bigint(19) unsigned DEFAULT NULL,
  `cost_per_play` float unsigned DEFAULT '0',
  `cost_per_unique_listener` float DEFAULT NULL,
  `cost` float DEFAULT NULL,
  `is_interruption` tinyint(1) DEFAULT '0',
  `is_request` tinyint(1) DEFAULT '0',
  `is_playprompt` tinyint(1) DEFAULT '0',
  `is_siptransfer` tinyint(1) DEFAULT '0',
  `is_perlistener` tinyint(1) DEFAULT '0',
  `is_perconference` tinyint(1) DEFAULT '0',
  `listener_is_first_time_interruption` tinyint(1) DEFAULT '0',
  `listener_is_first_time_request` tinyint(1) DEFAULT '0',
  `siptransfer_sip_string` varchar(255) DEFAULT NULL,
  `siptransfer_callid_mode` enum('CLEAN','LISTENERANI','LISTENERID') DEFAULT NULL,
  `siptransfer_callid_sent` varchar(255) DEFAULT NULL,
  `siptransfer_asterisk_dialstatus` char(32) DEFAULT NULL,
  `siptransfer_asterisk_hangupcause` char(16) DEFAULT NULL,
  `on_summary` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `date_start` (`date_start`),
  KEY `date_stop` (`date_stop`),
  KEY `campaign` (`campaign_id`,`date_start`),
  KEY `listener` (`listener_id`,`date_start`),
  KEY `log_call` (`log_call_id`),
  KEY `log_listen` (`log_listen_id`),
  KEY `on_summary` (`on_summary`)
) ENGINE=InnoDB AUTO_INCREMENT=201520 DEFAULT CHARSET=utf8;

CREATE TABLE `log_listen` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `server_id` bigint(19) unsigned DEFAULT NULL,
  `log_call_id` bigint(19) unsigned DEFAULT NULL,
  `date_start` datetime DEFAULT NULL,
  `date_stop` datetime DEFAULT NULL,
  `seconds` int(10) unsigned DEFAULT '0',
  `extension` char(16) DEFAULT NULL,
  `content_id` bigint(19) unsigned DEFAULT NULL,
  `gateway_conference_id` bigint(19) unsigned DEFAULT NULL,
  `on_summary` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `date_start` (`date_start`),
  KEY `date_stop` (`date_stop`),
  KEY `log_call` (`log_call_id`),
  KEY `content_id` (`content_id`,`date_start`),
  KEY `conference_id` (`gateway_conference_id`,`date_start`),
  KEY `on_summary` (`on_summary`)
) ENGINE=InnoDB AUTO_INCREMENT=926075 DEFAULT CHARSET=utf8;

CREATE TABLE `now_session` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `log_call_id` bigint(19) unsigned DEFAULT NULL,
  `log_listen_id` bigint(20) DEFAULT NULL,
  `log_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `log_campaign_siptransfer_id` bigint(19) unsigned DEFAULT NULL,
  `call_server_id` bigint(19) unsigned DEFAULT NULL,
  `call_date_start` datetime DEFAULT NULL,
  `call_asterisk_sip_ip` varchar(15) DEFAULT NULL,
  `call_asterisk_channel` char(64) DEFAULT NULL,
  `call_asterisk_uniqueid` char(64) DEFAULT NULL,
  `call_ani_e164` char(32) DEFAULT NULL,
  `call_did_e164` char(32) DEFAULT NULL,
  `call_listener_play_welcome` tinyint(1) DEFAULT '1',
  `call_listener_ani_id` bigint(19) unsigned DEFAULT NULL,
  `call_listener_id` bigint(19) unsigned DEFAULT NULL,
  `call_listener_is_anonymous` tinyint(1) DEFAULT NULL,
  `call_entryway_id` bigint(19) unsigned DEFAULT NULL,
  `call_gateway_id` bigint(19) unsigned DEFAULT NULL,
  `listen_active` tinyint(1) DEFAULT '0',
  `listen_date_start` datetime DEFAULT NULL,
  `listen_extension` char(16) DEFAULT NULL,
  `listen_content_id` bigint(19) unsigned DEFAULT NULL,
  `listen_gateway_conference_id` bigint(19) unsigned DEFAULT NULL,
  `listen_server_id` bigint(20) DEFAULT NULL,
  `listen_last_played_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `listen_last_played_campaign_timestamp` datetime DEFAULT NULL,
  `listen_last_played_campaign_log_id` bigint(19) unsigned DEFAULT NULL,
  `listen_last_played_campaigns_interruption_timestamps` char(255) DEFAULT NULL,
  `listen_asterisk_channel` char(64) DEFAULT NULL,
  `listen_asterisk_uniqueid` char(64) DEFAULT NULL,
  `engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `engine_date_start` datetime DEFAULT NULL,
  `engine_server_id` bigint(19) unsigned DEFAULT NULL,
  `engine_asterisk_channel` char(64) DEFAULT NULL,
  `engine_asterisk_uniqueid` char(64) DEFAULT NULL,
  `engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `next_step_1_engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `next_step_1_engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `next_step_1_engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `next_step_2_engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `next_step_2_engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `next_step_2_engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `last_engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `last_engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `last_engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `call_server` (`call_server_id`),
  KEY `date_start` (`call_date_start`),
  KEY `search_call_by_channel` (`call_asterisk_channel`,`call_server_id`)
) ENGINE=MEMORY AUTO_INCREMENT=661418 DEFAULT CHARSET=utf8;

CREATE TABLE `now_session_storage_errors` (
  `id` bigint(19) unsigned DEFAULT NULL,
  `log_call_id` bigint(19) unsigned DEFAULT NULL,
  `log_listen_id` bigint(20) DEFAULT NULL,
  `log_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `log_campaign_siptransfer_id` bigint(19) unsigned DEFAULT NULL,
  `call_server_id` bigint(19) unsigned DEFAULT NULL,
  `call_date_start` datetime DEFAULT NULL,
  `call_asterisk_sip_ip` varchar(15) DEFAULT NULL,
  `call_asterisk_channel` char(64) DEFAULT NULL,
  `call_asterisk_uniqueid` char(64) DEFAULT NULL,
  `call_ani_e164` char(32) DEFAULT NULL,
  `call_did_e164` char(32) DEFAULT NULL,
  `call_listener_play_welcome` tinyint(1) DEFAULT '1',
  `call_listener_ani_id` bigint(19) unsigned DEFAULT NULL,
  `call_listener_id` bigint(19) unsigned DEFAULT NULL,
  `call_listener_is_anonymous` tinyint(1) DEFAULT NULL,
  `call_entryway_id` bigint(19) unsigned DEFAULT NULL,
  `call_gateway_id` bigint(19) unsigned DEFAULT NULL,
  `listen_active` tinyint(1) DEFAULT '0',
  `listen_date_start` datetime DEFAULT NULL,
  `listen_extension` char(16) DEFAULT NULL,
  `listen_content_id` bigint(19) unsigned DEFAULT NULL,
  `listen_gateway_conference_id` bigint(19) unsigned DEFAULT NULL,
  `listen_server_id` bigint(20) DEFAULT NULL,
  `listen_last_played_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `listen_last_played_campaign_timestamp` datetime DEFAULT NULL,
  `listen_last_played_campaign_log_id` bigint(19) unsigned DEFAULT NULL,
  `listen_last_played_campaigns_interruption_timestamps` char(255) DEFAULT NULL,
  `listen_asterisk_channel` char(64) DEFAULT NULL,
  `listen_asterisk_uniqueid` char(64) DEFAULT NULL,
  `engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `engine_date_start` datetime DEFAULT NULL,
  `engine_server_id` bigint(19) unsigned DEFAULT NULL,
  `engine_asterisk_channel` char(64) DEFAULT NULL,
  `engine_asterisk_uniqueid` char(64) DEFAULT NULL,
  `engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `next_step_1_engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `next_step_1_engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `next_step_1_engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `next_step_2_engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `next_step_2_engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `next_step_2_engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `last_engine_type` enum('LISTEN','TALK','PRIVATETALK','ADVERTISE','ADVERTISESIPTRANSFER','HANGUP') DEFAULT NULL,
  `last_engine_advertise_trigger_type` enum('LISTENERMANUAL','LISTENERTIMEOUT','LISTENERPREROLL','LISTENERREQUEST','CONFERENCEMANUAL','CONFERENCETIMEOUT','CONFERENCEADREPLACE') DEFAULT NULL,
  `last_engine_campaign_id` bigint(19) unsigned DEFAULT NULL,
  `error_date` datetime DEFAULT NULL,
  `error_id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`error_id`),
  KEY `engine_now` (`engine_type`)
) ENGINE=InnoDB AUTO_INCREMENT=145472 DEFAULT CHARSET=utf8;

CREATE TABLE `summary_call` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `entryway_id` bigint(20) unsigned DEFAULT NULL,
  `listener_ani_carrier_id` bigint(20) unsigned DEFAULT NULL,
  `count` mediumint(9) unsigned DEFAULT NULL,
  `seconds` mediumint(9) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `e` (`entryway_id`),
  KEY `c` (`listener_ani_carrier_id`)
) ENGINE=InnoDB AUTO_INCREMENT=161 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `summary_campaign` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `campaign_id` bigint(19) unsigned DEFAULT NULL,
  `entryway_id` bigint(20) unsigned DEFAULT NULL,
  `gateway_id` bigint(20) unsigned DEFAULT NULL,
  `content_id` bigint(20) unsigned DEFAULT NULL,
  `count_interruption` mediumint(9) unsigned DEFAULT NULL,
  `count_request` mediumint(9) unsigned DEFAULT NULL,
  `count_request_siptransfer` mediumint(9) unsigned DEFAULT NULL,
  `seconds_interruption` mediumint(8) unsigned DEFAULT NULL,
  `seconds_request` mediumint(8) unsigned DEFAULT NULL,
  `seconds_request_siptransfer` mediumint(8) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `e` (`entryway_id`),
  KEY `g` (`gateway_id`),
  KEY `c` (`content_id`),
  KEY `ad` (`campaign_id`)
) ENGINE=InnoDB AUTO_INCREMENT=161 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `summary_listen` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `entryway_id` bigint(20) unsigned DEFAULT NULL,
  `gateway_id` bigint(20) unsigned DEFAULT NULL,
  `content_id` bigint(20) unsigned DEFAULT NULL,
  `count` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_10sec` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_1min` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_5min` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_20min` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_1hr` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_2hr` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_6hr` mediumint(9) unsigned DEFAULT NULL,
  `count_acd_more6hr` mediumint(9) unsigned DEFAULT NULL,
  `seconds` mediumint(9) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`),
  KEY `e` (`entryway_id`),
  KEY `g` (`gateway_id`),
  KEY `c` (`content_id`)
) ENGINE=InnoDB AUTO_INCREMENT=161 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sys_config` (
  `group` char(64) NOT NULL,
  `name` char(128) NOT NULL,
  `value` char(255) DEFAULT NULL,
  PRIMARY KEY (`group`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sys_server` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `short_title` char(16) DEFAULT NULL,
  `ip` char(15) DEFAULT NULL,
  `location_id` bigint(19) unsigned DEFAULT NULL,
  `engine_media_remote_ip` char(200) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `flag_no_listener_preroll_ad` tinyint(1) DEFAULT '0',
  `flag_no_listener_timeout_ad` tinyint(1) DEFAULT '0',
  `flag_no_add_siptransfer` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_sys_server_1_idx` (`location_id`),
  CONSTRAINT `location` FOREIGN KEY (`location_id`) REFERENCES `sys_server_location` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=161127 DEFAULT CHARSET=utf8;

CREATE TABLE `sys_server_location` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `sys_user` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `permission_id` bigint(20) unsigned DEFAULT NULL,
  `title` char(255) DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `encrypted_password` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `reset_password_token` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `reset_password_sent_at` datetime DEFAULT NULL,
  `remember_created_at` datetime DEFAULT NULL,
  `sign_in_count` int(11) DEFAULT '0',
  `current_sign_in_at` datetime DEFAULT NULL,
  `last_sign_in_at` datetime DEFAULT NULL,
  `current_sign_in_ip` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `last_sign_in_ip` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `failed_attempts` int(11) DEFAULT '0',
  `unlock_token` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `locked_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `landline` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `cellphone` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sys_user_1_idx` (`permission_id`),
  KEY `fk_sys_user_1_idx1` (`permission_id`),
  CONSTRAINT `fk_sys_user_1` FOREIGN KEY (`permission_id`) REFERENCES `sys_user_permission` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1102847 DEFAULT CHARSET=utf8;

CREATE TABLE `sys_user_permission` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `title` char(200) DEFAULT NULL,
  `is_super_user` tinyint(1) DEFAULT '0',
  `can_manage_specific_3rdparty_resources` tinyint(1) DEFAULT '0',
  `can_manage_specific_broadcast_resources` tinyint(1) DEFAULT '0',
  `can_manage_specific_rca_resources` tinyint(1) DEFAULT '0',
  `can_manage_all_zenoradio_data` tinyint(1) DEFAULT '0',
  `can_manage_all_zenoradio_metadata` tinyint(1) DEFAULT '0',
  `can_manage_all_zenoradio_users` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `sys_user_resource_3rdparty` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(19) unsigned DEFAULT NULL,
  `3rdparty_id` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sys_user_resource_3rdparty_2_idx` (`3rdparty_id`),
  KEY `fk_sys_user_resource_3rdparty_1_idx` (`user_id`),
  CONSTRAINT `fk_sys_user_resource_3rdparty_1` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_user_resource_3rdparty_2` FOREIGN KEY (`3rdparty_id`) REFERENCES `zenoradio-v25`.`data_group_3rdparty` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1089658 DEFAULT CHARSET=utf8;

CREATE TABLE `sys_user_resource_advertise_agency` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(19) unsigned DEFAULT NULL,
  `advertise_agency_id` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sys_user_resource_advertise_agency_2_idx` (`advertise_agency_id`),
  KEY `fk_sys_user_resource_advertise_agency_1_idx` (`user_id`),
  CONSTRAINT `fk_sys_user_resource_advertise_agency_1` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_user_resource_advertise_agency_2` FOREIGN KEY (`advertise_agency_id`) REFERENCES `zenoradio-v25`.`data_group_advertise_agency` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sys_user_resource_broadcast` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(19) unsigned DEFAULT NULL,
  `broadcast_id` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sys_user_resource_broadcast_2_idx` (`broadcast_id`),
  KEY `fk_sys_user_resource_broadcast_1_idx` (`user_id`),
  CONSTRAINT `fk_sys_user_resource_broadcast_1` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_user_resource_broadcast_2` FOREIGN KEY (`broadcast_id`) REFERENCES `zenoradio-v25`.`data_group_broadcast` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1102847 DEFAULT CHARSET=utf8;

CREATE TABLE `sys_user_resource_rca` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(19) unsigned DEFAULT NULL,
  `rca_id` bigint(19) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sys_user_resource_rca_1_idx1` (`rca_id`),
  KEY `fk_sys_user_resource_rca_1_idx` (`user_id`),
  CONSTRAINT `fk_sys_user_resource_rca_1` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `rca` FOREIGN KEY (`rca_id`) REFERENCES `zenoradio-v25`.`data_group_rca` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1095227 DEFAULT CHARSET=utf8;

